### ISSUE TITLE
Consider comparing with other string libraries

### ISSUE THREAD

**Issue by michaelmior** [boyerjohn/rapidstring#10]
Looks very cool!  I'd be interested in seeing how this compares to other libraries such as [sds](https://github.com/antirez/sds).

**Comment by boyerjohn** [comment]
SDS cannot compile in C++, therefore it cannot be tested in google benchmark and it uses GCC extensions, which means it won't be able to be tested on ICC or MSVC.

A few months ago, I tried tweaking SDS to allow it to compile in C++, and the results were that SDS was several times slower than rapidstring. That library wasn't built for speed.

Would you happen to know of any platform independent string libraries which don't use custom allocators (such as Facebook's folly string)?

**Comment by michaelmior** [comment]
Nothing else comes to mind. Although I think it would be helpful to compare with folly and other libraries even if they do use a custom allocator.

**Comment by boyerjohn** [comment]
Comparing against a custom allocator would entirely void the comparison as 60%+ of the CPU time is spent inside `realloc()` in my benchmarks. I would essentially be benchmarking folly's allocator vs the standard allocator.
