### ISSUE TITLE
Adding support to UTF-8 ! 

### ISSUE THREAD

**Issue by LifeIsStrange** [boyerjohn/rapidstring#8]
Via the C11 u8 type or via a UTF lib/Unicode

Once the library support UTF-8 it should be used everywhere !!

**Comment by boyerjohn** [comment]
`u8` is not a type, it's a string literal. Furthemore, the library currently supports unicode, it just doesn't implement any of the abstractions around it, like `std::string`. It is essentially a buffer manipulation library. If anyone needs unicode helper functions, they can implement it themselves on top of the library.
